INSERT INTO public.country_code (country_code,country,region,remarks) VALUES
	 ('AF','Afghanistan','',''),
	 ('AX','Aland Islands','',''),
	 ('AL','Albania','',''),
	 ('DZ','Algeria','',''),
	 ('AD','Andorra','',''),
	 ('AO','Angola','',''),
	 ('AG','Antigua and Barbuda','',''),
	 ('AR','Argentina','',''),
	 ('AM','Armenia','',''),
	 ('AW','Aruba','','');
INSERT INTO public.country_code (country_code,country,region,remarks) VALUES
	 ('AT','Austria','',''),
	 ('AZ','Azerbaijan','',''),
	 ('BS','Bahamas','',''),
	 ('BH','Bahrain','',''),
	 ('BB','Barbados','',''),
	 ('BY','Belarus','',''),
	 ('BE','Belgium','',''),
	 ('BZ','Belize','',''),
	 ('BJ','Benin','',''),
	 ('BM','Bermuda','','');
INSERT INTO public.country_code (country_code,country,region,remarks) VALUES
	 ('BO','Bolivia','',''),
	 ('BA','Bosnia and Herzegovina','',''),
	 ('BW','Botswana','',''),
	 ('BR','Brazil','',''),
	 ('VG','British Virgin Islands','',''),
	 ('BN','Brunei Darussalam','',''),
	 ('BG','Bulgaria','',''),
	 ('BF','Burkina Faso','',''),
	 ('BI','Burundi','',''),
	 ('CM','Cameroon','','');
INSERT INTO public.country_code (country_code,country,region,remarks) VALUES
	 ('CA','Canada','',''),
	 ('CV','Cape Verde','',''),
	 ('KY','Cayman Islands','',''),
	 ('CF','Central African Republic','',''),
	 ('TD','Chad','',''),
	 ('CL','Chile','',''),
	 ('CO','Colombia','',''),
	 ('KM','Comoros','',''),
	 ('CG','Congo','',''),
	 ('CR','Costa Rica','','');
INSERT INTO public.country_code (country_code,country,region,remarks) VALUES
	 ('HR','Croatia','',''),
	 ('CU','Cuba','',''),
	 ('CY','Cyprus','',''),
	 ('CZ','Czech Republic','',''),
	 ('CD','Democratic Republic of Congo','',''),
	 ('DK','Denmark','',''),
	 ('DJ','Djibouti','',''),
	 ('DM','Dominica','',''),
	 ('DO','Dominican Republic','',''),
	 ('EC','Ecuador','','');
INSERT INTO public.country_code (country_code,country,region,remarks) VALUES
	 ('EG','Egypt','',''),
	 ('SV','El Salvador','',''),
	 ('GQ','Equatorial Guinea','',''),
	 ('EE','Estonia','',''),
	 ('ET','Ethiopia','',''),
	 ('FI','Finland','',''),
	 ('FR','France','',''),
	 ('GF','French Guiana','',''),
	 ('TF','French Southern and Antarctic Lands','',''),
	 ('GA','Gabon','','');
INSERT INTO public.country_code (country_code,country,region,remarks) VALUES
	 ('GM','Gambia','',''),
	 ('GE','Georgia','',''),
	 ('DE','Germany','',''),
	 ('GH','Ghana','',''),
	 ('GI','Gibraltar','',''),
	 ('GR','Greece','',''),
	 ('GD','Grenada','',''),
	 ('GP','Guadeloupe','',''),
	 ('GT','Guatemala','',''),
	 ('GN','Guinea','','');
INSERT INTO public.country_code (country_code,country,region,remarks) VALUES
	 ('GW','Guinea-Bissau','',''),
	 ('GY','Guyana','',''),
	 ('HT','Haiti','',''),
	 ('HN','Honduras','',''),
	 ('HU','Hungary','',''),
	 ('IS','Iceland','',''),
	 ('IQ','Iraq','',''),
	 ('IE','Ireland','',''),
	 ('IL','Israel','',''),
	 ('IT','Italy','','');
INSERT INTO public.country_code (country_code,country,region,remarks) VALUES
	 ('CI','Ivory Coast','',''),
	 ('JM','Jamaica','',''),
	 ('JP','Japan','',''),
	 ('JO','Jordan','',''),
	 ('KZ','Kazakhstan','',''),
	 ('KE','Kenya','',''),
	 ('KW','Kuwait','',''),
	 ('KG','Kyrgyzstan','',''),
	 ('LV','Latvia','',''),
	 ('LB','Lebanon','','');
INSERT INTO public.country_code (country_code,country,region,remarks) VALUES
	 ('LS','Lesotho','',''),
	 ('LR','Liberia','',''),
	 ('LY','Libya','',''),
	 ('LI','Liechtenstein','',''),
	 ('LT','Lithuania','',''),
	 ('LU','Luxembourg','',''),
	 ('MK','Macedonia','',''),
	 ('MG','Madagascar','',''),
	 ('MW','Malawi','',''),
	 ('MV','Maldives','','');
INSERT INTO public.country_code (country_code,country,region,remarks) VALUES
	 ('ML','Mali','',''),
	 ('MT','Malta','',''),
	 ('MQ','Martinique','',''),
	 ('MR','Mauritania','',''),
	 ('MU','Mauritius','',''),
	 ('YT','Mayotte','',''),
	 ('MX','Mexico','',''),
	 ('FM','Micronesia','',''),
	 ('MC','Monaco','',''),
	 ('MN','Mongolia','','');
INSERT INTO public.country_code (country_code,country,region,remarks) VALUES
	 ('ME','Montenegro','',''),
	 ('MA','Morocco','',''),
	 ('MZ','Mozambique','',''),
	 ('NA','Namibia','',''),
	 ('NP','Nepal','',''),
	 ('NL','Netherlands','',''),
	 ('AN','Netherlands Antilles','',''),
	 ('NI','Nicaragua','',''),
	 ('NE','Niger','',''),
	 ('NG','Nigeria','','');
INSERT INTO public.country_code (country_code,country,region,remarks) VALUES
	 ('KP','North Korea','',''),
	 ('NO','Norway','',''),
	 ('OM','Oman','',''),
	 ('PK','Pakistan','',''),
	 ('PS','Palestine','',''),
	 ('PA','Panama','',''),
	 ('PY','Paraguay','',''),
	 ('PE','Peru','',''),
	 ('PL','Poland','',''),
	 ('PT','Portugal','','');
INSERT INTO public.country_code (country_code,country,region,remarks) VALUES
	 ('PR','Puerto Rico','',''),
	 ('QA','Qatar','',''),
	 ('MD','Republic of Moldova','',''),
	 ('RS','Republic of Serbia','',''),
	 ('RE','Reunion','',''),
	 ('RO','Romania','',''),
	 ('RU','Russia','',''),
	 ('RW','Rwanda','',''),
	 ('SH','Saint Helena','',''),
	 ('KN','Saint Kitts and Nevis','','');
INSERT INTO public.country_code (country_code,country,region,remarks) VALUES
	 ('LC','Saint Lucia','',''),
	 ('SX','Saint Martin (Dutch part)','',''),
	 ('PM','Saint Pierre and Miquelon','',''),
	 ('VC','Saint Vincent and the Grenadines','',''),
	 ('SA','Saudi Arabia','',''),
	 ('SN','Senegal','',''),
	 ('SC','Seychelles','',''),
	 ('SL','Sierra Leone','',''),
	 ('SK','Slovakia','',''),
	 ('SI','Slovenia','','');
INSERT INTO public.country_code (country_code,country,region,remarks) VALUES
	 ('SO','Somalia','',''),
	 ('ZA','South Africa','',''),
	 ('GS','South Georgia and South Sandwich Islands','',''),
	 ('SS','South Sudan','',''),
	 ('ES','Spain','',''),
	 ('SD','Sudan','',''),
	 ('SR','Suriname','',''),
	 ('SZ','Swaziland','',''),
	 ('SE','Sweden','',''),
	 ('CH','Switzerland','','');
INSERT INTO public.country_code (country_code,country,region,remarks) VALUES
	 ('TZ','Tanzania','',''),
	 ('TG','Togo','',''),
	 ('TT','Trinidad and Tobago','',''),
	 ('TN','Tunisia','',''),
	 ('TR','Turkey','',''),
	 ('TM','Turkmenistan','',''),
	 ('UG','Uganda','',''),
	 ('UA','Ukraine','',''),
	 ('AE','United Arab Emirates','',''),
	 ('GB','United Kingdom','','');
INSERT INTO public.country_code (country_code,country,region,remarks) VALUES
	 ('US','United States','',''),
	 ('UY','Uruguay','',''),
	 ('UZ','Uzbekistan','',''),
	 ('VE','Venezuela','',''),
	 ('EH','Western Sahara','',''),
	 ('YE','Yemen Republic','',''),
	 ('ZM','Zambia','',''),
	 ('ZW','Zimbabwe','',''),
	 ('ER','Eritrea','',''),
	 ('FO','Faroe Islands','','');
INSERT INTO public.country_code (country_code,country,region,remarks) VALUES
	 ('GL','Greenland','',''),
	 ('IM','Isle of Man','',''),
	 ('IO','British Indian Ocean Territory','',''),
	 ('IR','Iran','',''),
	 ('MO','Macao','',''),
	 ('ST','Sao Tome and Principe','',''),
	 ('SY','Syrian Arab Republic','',''),
	 ('TC','Turks and Caicos Islands','',''),
	 ('TJ','Tajikistan','',''),
	 ('TL','Timor-Leste','','');
INSERT INTO public.country_code (country_code,country,region,remarks) VALUES
	 ('TP','East Timor','',''),
	 ('BT','Bhutan','','Manually Included'),
	 ('AS','American Samoa','Pacific',''),
	 ('AU','Australia','Pacific',''),
	 ('BD','Bangladesh','India',''),
	 ('KH','Cambodia','ASIA',''),
	 ('CN','China','CHINA',''),
	 ('CK','Cook Islands','Pacific',''),
	 ('FJ','Fiji','Pacific',''),
	 ('PF','French Polynesia','Pacific','');
INSERT INTO public.country_code (country_code,country,region,remarks) VALUES
	 ('GU','Guam','Pacific',''),
	 ('HK','Hong Kong China','CHINA',''),
	 ('IN','India','India',''),
	 ('ID','Indonesia','ASIA',''),
	 ('KI','Kiribati','Pacific',''),
	 ('LA','Laos','ASIA',''),
	 ('MY','Malaysia','ASIA',''),
	 ('MH','Marshall Islands','Pacific',''),
	 ('MM','Myanmar','ASIA',''),
	 ('NC','New Caledonia','Pacific','');
INSERT INTO public.country_code (country_code,country,region,remarks) VALUES
	 ('NZ','New Zealand','Pacific',''),
	 ('PG','Papua New Guinea','Pacific',''),
	 ('PH','Philippines','ASIA',''),
	 ('WS','Samoa','Pacific',''),
	 ('SG','Singapore','ASIA',''),
	 ('KR','South Korea','ASIA',''),
	 ('LK','Sri Lanka','India',''),
	 ('TW','Taiwan','ASIA',''),
	 ('TH','Thailand','ASIA',''),
	 ('TO','Tonga','Pacific','');
INSERT INTO public.country_code (country_code,country,region,remarks) VALUES
	 ('TV','Tuvalu','Pacific',''),
	 ('VU','Vanuatu','Pacific',''),
	 ('VN','Viet Nam','ASIA',''),
	 ('PISL','Pacific Islands Solomon Islands','Pacific','Manually Included');
